version: '3.8'

services:
  app:
    container_name: hack-u-api
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/opt
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: hack-u-db
    volumes:
      - db-data:/var/lib/postgresql/hacku_development/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  db-data: